name: link_people
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Other
  html: ^0.15.0
  flutter_html: ^2.2.1
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  flutter_vector_icons: ^1.0.0
  package_info_plus: ^1.4.2
  carousel_slider: ^4.1.1
  custom_line_indicator_bottom_navbar: ^0.0.8
  styled_text: ^5.1.0
  flutter_staggered_grid_view: ^0.6.1
  file_picker: ^4.5.1
  image_picker: ^0.8.5
  photo_view: ^0.13.0

  #State Management
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  mobx_codegen: ^2.0.6
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - Images/
    - Images/ReactionIcon/
    - Images/timeline/
    - Images/people/
    - Images/pages/cover/
    - Images/pages/profile/

  fonts:
    - family: Raleway
      fonts:
        - asset: Font/SansSerif.ttf
